### ISSUE TITLE
ABP vNext support

### ISSUE THREAD

**Issue by wakuflair** [wakuflair/ABPHelper#4]
Plan to support ABP vNext when it's steady(may be v1.0)

**Comment by XuJin186** [comment]
> 计划在稳定时支持ABP vNext（可能是v1.0）

请问你开发代码生成器了吗

**Comment by wakuflair** [comment]
还没有，因为会有官方的工具，所以还在观望。

**Comment by xujin950710** [comment]
> 还没有，因为会有官方的工具，所以还在观望。

应该不会了  最多也就支持后端生成  要不然我们两合力开发一个吧 我微信13705106052

**Comment by XuJin186** [comment]
> 还没有，因为会有官方的工具，所以还在观望。

应该不会    官方支持的只支持它自己的前端   我们自己肯定不是用免费那套  所以要不然我们两合力开发一套吧   我微信13705106052

**Comment by wakuflair** [comment]
> > 还没有，因为会有官方的工具，所以还在观望。
> 
> 应该不会 官方支持的只支持它自己的前端 我们自己肯定不是用免费那套 所以要不然我们两合力开发一套吧 我微信13705106052

官方的工具, 是商业版中的一个[套件](https://commercial.abp.io/tools/suite), 功能应该会很全面.
我想尽量避免开发与之重复的功能, 所以在等它发布后, 再决定开发的内容.

**Comment by wakuflair** [comment]
We created a new tool named [EasyAbp.AbpHelper](https://github.com/EasyAbp/AbpHelper.CLI). It supports ABP vNext, have a try!
