### ISSUE TITLE
你还会继续开发一下吗,我也打算做一个abp的代码生成插件

### ISSUE THREAD

**Issue by neozhu** [wakuflair/ABPHelper#5]

**Comment by wakuflair** [comment]
你好 @neozhu 
对于现在的Asp.net Boilerplate框架不, ABPHelper不打算继续开发新功能了.
准备支持ABP vNext, 当然得等它1.0正式发布后.

#4

**Comment by neozhu** [comment]
👍!有时间要好好研究的你这个插件,我做过一个mvc5 scaffolding 的插件,到了.net core下完全不能用,看来还是要走com plugin这条路.谢谢你
