### ISSUE TITLE
代码无法运行

### ISSUE THREAD

**Issue by 312977** [wakuflair/ABPHelper#6]
你好 是不是非vs2019编写的vs插件 在vs2019编译时候都会有问题呀？ 启动源码 提示 
该项目中不存在目标“GenerateFileManifest”。			
？？？求解决 
我想写一套前后台代码一起生成的插件，可以选模板 非生成一套

**Comment by wakuflair** [comment]
你好, 这个插件是用VS2017编写的, VS2019编译可能会有问题.
如果使用ABP vNext, 请见https://github.com/EasyAbp/AbpHelper.CLI
